// Embed /prompts/*.md into lib/prompts-data.ts at build time.
// The .md files stay the single source of truth (edit those); this makes
// the serverless bundle self-sufficient — no filesystem, no tracing config.
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const dir = path.join(root, "prompts");
const out = path.join(root, "lib", "prompts-data.ts");

const data = {};
for (const f of fs.readdirSync(dir).filter((f) => f.endsWith(".md"))) {
  data[f.replace(/\.md$/, "")] = fs.readFileSync(path.join(dir, f), "utf8");
}

fs.writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/embed-prompts.mjs — edit /prompts/*.md instead.\n` +
    `export const PROMPTS: Record<string, string> = ${JSON.stringify(data, null, 2)};\n`,
);
console.log(`[embed-prompts] embedded ${Object.keys(data).length} prompts → lib/prompts-data.ts`);
